import React, { useRef } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Copy, CheckCheck, Bot, Clock, Users, Sparkles } from 'lucide-react'
import useStore      from '../store/useStore.js'
import useAgentStore from '../store/useAgentStore.js'
import GlassCard     from './GlassCard.jsx'

const AIOutput = () => {
  const { aiOutput, showOutput, generationMetadata, executedAgentName } = useStore()
  const { selectedAgent } = useAgentStore()
  const [copied, setCopied] = React.useState(false)
  const contentRef = useRef(null)

  if (!showOutput || !aiOutput) return null

  function handleCopy() {
    navigator.clipboard.writeText(aiOutput).catch(console.error)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const genTime = generationMetadata?.evalDuration
    ? `${(generationMetadata.evalDuration / 1e9).toFixed(1)}s` : null
  const tokensPerSec = generationMetadata?.evalCount && generationMetadata?.evalDuration
    ? `${(generationMetadata.evalCount / (generationMetadata.evalDuration / 1e9)).toFixed(1)} tok/s` : null

  const agentLabel = executedAgentName || selectedAgent?.name || 'AI Agent'

  return (
    <AnimatePresence>
      <motion.div key="ai-output" initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: -20 }} transition={{ duration: 0.5, ease: 'easeOut' }}>
        <GlassCard hover glowColor="blue" delay={0}>

          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center">
                <Bot size={18} className="text-blue-400" />
              </div>

              <div>
                <div className="flex items-center gap-2 flex-wrap">
                  <h3 className="text-sm font-semibold text-white/90">AI Output</h3>

                  <span className="inline-flex items-center gap-1 text-[10px] font-semibold
                    text-purple-300 bg-purple-500/15 border border-purple-500/20
                    px-2 py-0.5 rounded-full">
                    <Sparkles size={8} />
                    {agentLabel}
                  </span>

                  {generationMetadata?.model && (
                    <span className="text-[10px] font-medium text-white/55
                      bg-white/[0.06] border border-white/[0.08]
                      px-2 py-0.5 rounded-full">
                      {generationMetadata.model}
                    </span>
                  )}
                </div>

                <div className="flex items-center gap-3 mt-0.5 flex-wrap">
                  <p className="text-xs text-white/50">Generated by AI agent</p>
                  {genTime && (
                    <span className="flex items-center gap-1 text-[10px] text-white/40">
                      <Clock size={9} />
                      {genTime}
                    </span>
                  )}
                  {tokensPerSec && (
                    <span className="text-[10px] text-white/40">{tokensPerSec}</span>
                  )}
                </div>
              </div>
            </div>

            <motion.button whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}
              onClick={handleCopy}
              className="p-2 rounded-lg hover:bg-white/[0.07] text-white/40 hover:text-white/80
                transition-all duration-200"
              aria-label="Copy output">
              {copied ? <CheckCheck size={15} className="text-green-400" /> : <Copy size={15} />}
            </motion.button>
          </div>

          <motion.div initial={{ opacity: 0, x: -6 }} animate={{ opacity: 1, x: 0 }}
            transition={{ delay: 0.2 }}
            className="flex items-center gap-2 mb-3 px-1">
            <Users size={13} className="text-purple-400/70 flex-shrink-0" />
            <span className="text-[11px] text-white/55 font-medium">
              5 AI agents collaborated to generate this result
            </span>
          </motion.div>

          <div className="relative">
            <div ref={contentRef}
              className="max-h-[480px] overflow-y-auto rounded-xl bg-white/[0.02] border border-white/[0.05] p-5">
              <MarkdownRenderer content={aiOutput} />
            </div>
            <div className="absolute bottom-0 left-0 right-0 h-8 bg-gradient-to-t from-[#0e0e1a]/60
              to-transparent rounded-b-xl pointer-events-none" />
          </div>

          {(generationMetadata?.evalCount || genTime || tokensPerSec) && (
            <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.4 }}
              className="mt-3 flex items-center gap-3 flex-wrap">
              {generationMetadata?.evalCount && (
                <span className="text-[10px] text-white/50 bg-white/[0.04] border border-white/[0.06] px-2 py-0.5 rounded-md">
                  📝 {generationMetadata.evalCount} tokens
                </span>
              )}
              {genTime && (
                <span className="text-[10px] text-white/50 bg-white/[0.04] border border-white/[0.06] px-2 py-0.5 rounded-md">
                  ⏱ {genTime} generation
                </span>
              )}
              {tokensPerSec && (
                <span className="text-[10px] text-white/50 bg-white/[0.04] border border-white/[0.06] px-2 py-0.5 rounded-md">
                  🚀 {tokensPerSec}
                </span>
              )}
            </motion.div>
          )}
        </GlassCard>
      </motion.div>
    </AnimatePresence>
  )
}

function MarkdownRenderer({ content }) {
  if (!content) return null

  const lines    = content.split('\n')
  const elements = []
  let codeBlock  = false
  let codeLines  = []
  let codeLang   = ''
  let codeKey    = 0

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]

    if (line.startsWith('```')) {
      if (!codeBlock) {
        codeBlock = true
        codeLang  = line.replace('```', '').trim()
        codeLines = []
      } else {
        codeBlock = false
        elements.push(
          <div key={`code-${codeKey++}`} className="my-4 rounded-xl overflow-hidden border border-white/[0.08]">
            {codeLang && (
              <div className="px-4 py-1.5 bg-white/[0.04] border-b border-white/[0.06]">
                <span className="text-[10px] font-mono text-purple-300 uppercase">{codeLang}</span>
              </div>
            )}
            <pre className="p-4 overflow-x-auto bg-white/[0.02]">
              <code className="text-xs font-mono text-white/80 leading-relaxed">
                {codeLines.join('\n')}
              </code>
            </pre>
          </div>
        )
        codeLines = []
        codeLang  = ''
      }
      continue
    }

    if (codeBlock) { codeLines.push(line); continue }

    if (line.startsWith('## ')) {
      elements.push(
        <motion.h2 key={i} initial={{ opacity: 0, y: 4 }} animate={{ opacity: 1, y: 0 }}
          transition={{ delay: i * 0.008 }}
          className="text-base font-bold text-gradient mt-5 mb-2 first:mt-0">
          {line.replace(/^## /, '')}
        </motion.h2>
      )
      continue
    }

    if (line.startsWith('### ')) {
      elements.push(
        <h3 key={i} className="text-sm font-semibold text-white/85 mt-4 mb-1.5">
          {line.replace(/^### /, '')}
        </h3>
      )
      continue
    }

    if (line.startsWith('#### ')) {
      elements.push(
        <h4 key={i} className="text-sm font-medium text-white/70 mt-3 mb-1">
          {line.replace(/^#### /, '')}
        </h4>
      )
      continue
    }

    if (/^[-•*]\s/.test(line)) {
      const text = line.replace(/^[-•*]\s/, '')
      elements.push(
        <div key={i} className="flex items-start gap-2.5 mb-1.5 ml-2">
          <span className="text-purple-400/70 mt-[7px] text-[5px] flex-shrink-0">●</span>
          <span className="text-sm text-white/75 leading-relaxed"
            dangerouslySetInnerHTML={{ __html: inlineMarkdown(text) }} />
        </div>
      )
      continue
    }

    if (line.startsWith('→ ') || line.startsWith('> ')) {
      const text = line.replace(/^[→>]\s/, '')
      elements.push(
        <div key={i} className="flex items-start gap-2.5 mb-1.5 ml-2">
          <span className="text-blue-400/80 text-sm flex-shrink-0 mt-px">→</span>
          <span className="text-sm text-white/75 leading-relaxed"
            dangerouslySetInnerHTML={{ __html: inlineMarkdown(text) }} />
        </div>
      )
      continue
    }

    if (/^\d+[.)]\s/.test(line)) {
      const num  = line.match(/^(\d+)/)[1]
      const text = line.replace(/^\d+[.)]\s/, '')
      elements.push(
        <div key={i} className="flex items-start gap-2.5 mb-1.5 ml-2">
          <span className="text-purple-400 text-xs font-mono font-semibold flex-shrink-0 mt-0.5 min-w-[16px]">
            {num}.
          </span>
          <span className="text-sm text-white/75 leading-relaxed"
            dangerouslySetInnerHTML={{ __html: inlineMarkdown(text) }} />
        </div>
      )
      continue
    }

    if (/^\*[^*].*[^*]\*$/.test(line.trim())) {
      elements.push(
        <p key={i} className="text-xs text-white/45 italic mt-3 mb-1">
          {line.trim().replace(/^\*|\*$/g, '')}
        </p>
      )
      continue
    }

    if (/^[-*]{3,}$/.test(line.trim())) {
      elements.push(<div key={i} className="my-4 h-px bg-white/[0.08]" />)
      continue
    }

    if (line.trim() === '') {
      elements.push(<div key={i} className="h-2" />)
      continue
    }

    elements.push(
      <p key={i} className="text-sm text-white/75 leading-relaxed mb-1"
        dangerouslySetInnerHTML={{ __html: inlineMarkdown(line) }} />
    )
  }

  return <div className="space-y-0.5">{elements}</div>
}

function inlineMarkdown(text) {
  return text
    .replace(/\*\*(.*?)\*\*/g, '<strong class="text-white/90 font-semibold">$1</strong>')
    .replace(/\*(.*?)\*/g, '<em class="text-white/65 italic">$1</em>')
    .replace(/`(.*?)`/g, '<code class="text-purple-300 bg-purple-500/12 px-1 py-0.5 rounded text-[11px] font-mono">$1</code>')
    .replace(/✅/g, '<span class="text-green-400">✅</span>')
    .replace(/❌/g, '<span class="text-red-400">❌</span>')
    .replace(/⚠️/g, '<span class="text-yellow-400">⚠️</span>')
}

export default AIOutput